blocked by
thread 'main' panicked at /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/ion/data_structures.rs:510:14:
trying to get a VReg before observing its class
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/option.rs:1995:5
   5: core::option::Option<T>::expect
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/option.rs:896:21
   6: regalloc2::ion::data_structures::Env<F>::vreg
             at /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/ion/data_structures.rs:508:21
   7: regalloc2::ion::merge::<impl regalloc2::ion::data_structures::Env<F>>::merge_vreg_bundles
             at /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/ion/merge.rs:294:23
   8: regalloc2::ion::<impl regalloc2::ion::data_structures::Env<F>>::init
             at /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/ion/mod.rs:101:9
   9: regalloc2::ion::run
             at /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/ion/mod.rs:133:5
  10: regalloc2::run
             at /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/lib.rs:1515:5
  11: kecc::asmgen::translate_function
             at ./src/asmgen/mod.rs:398:18
  12: <kecc::asmgen::Asmgen as kecc::utils::Translate<kecc::ir::TranslationUnit>>::translate
             at ./src/asmgen/mod.rs:141:23
  13: kecc::compile_ir
             at ./bin/kecc.rs:222:27
  14: kecc::main
             at ./bin/kecc.rs:99:9
  15: core::ops::function::FnOnce::call_once
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.