blocked by
[testing "examples/ir2/bitwise.ir"]
test test_examples_asmgen_small ... FAILED

failures:

failures:
    test_examples_asmgen_small

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 11 filtered out; finished in 31.83s

--- STDERR:              kecc::test_examples test_examples_asmgen_small ---
thread 'test_examples_asmgen_small' panicked at src/asmgen/mod.rs:5455:77:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/panicking.rs:144:5
   3: core::option::unwrap_failed
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/option.rs:1985:5
   4: core::option::Option<T>::unwrap
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/option.rs:933:21
   5: kecc::asmgen::load_operand_to_reg
             at ./src/asmgen/mod.rs:5455:55
   6: kecc::asmgen::translate_block
             at ./src/asmgen/mod.rs:5176:23
   7: kecc::asmgen::translate_function
             at ./src/asmgen/mod.rs:959:28
   8: <kecc::asmgen::Asmgen as kecc::utils::Translate<kecc::ir::TranslationUnit>>::translate
             at ./src/asmgen/mod.rs:143:23
   9: kecc::tests::test_asmgen
             at ./src/tests.rs:300:19
  10: test_examples::test_examples_asmgen_small::{{closure}}
             at ./tests/test_examples.rs:214:17
  11: test_examples::test_dir
             at ./tests/test_examples.rs:20:9
  12: test_examples::test_examples_asmgen_small
             at ./tests/test_examples.rs:207:9
  13: test_examples::test_examples_asmgen_small::{{closure}}
             at ./tests/test_examples.rs:205:32
  14: core::ops::function::FnOnce::call_once
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/ops/function.rs:250:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

   Canceling due to test failure