blocked by RUST_LOG=trace RUST_BACKTRACE=1 cargo r --bin kecc --features="build-bin" -- examples/ir2/fib4.ir
thread 'main' panicked at src/asmgen/helper.rs:271:48:
%b8:p1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/option.rs:1995:5
   5: core::option::Option<T>::expect
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/option.rs:896:21
   6: <kecc::asmgen::helper::Gape as regalloc2::Function>::block_params::{{closure}}
             at ./src/asmgen/helper.rs:271:18
   7: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/iter/adapters/map.rs:89:28
   8: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold::enumerate::{{closure}}
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/iter/adapters/enumerate.rs:107:27
   9: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/slice/iter/macros.rs:232:27
  10: <core::iter::adapters::enumerate::Enumerate<I> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/iter/adapters/enumerate.rs:113:9
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/iter/adapters/map.rs:129:9
  12: core::iter::traits::iterator::Iterator::for_each
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/iter/traits/iterator.rs:848:9
  13: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/alloc/src/vec/mod.rs:2965:17
  14: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/alloc/src/vec/spec_extend.rs:26:9
  15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/alloc/src/vec/spec_from_iter.rs:33:9
  17: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/alloc/src/vec/mod.rs:2839:9
  18: core::iter::traits::iterator::Iterator::collect
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/iter/traits/iterator.rs:2034:9
  19: <kecc::asmgen::helper::Gape as regalloc2::Function>::block_params
             at ./src/asmgen/helper.rs:265:9
  20: regalloc2::ssa::validate_ssa
             at /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/ssa.rs:28:23
  21: regalloc2::ion::run
             at /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/ion/mod.rs:129:9
  22: regalloc2::run
             at /home/fish/.cargo/registry/src/index.crates.io-6f17d22bba15001f/regalloc2-0.9.3/src/lib.rs:1515:5
  23: kecc::asmgen::translate_function
             at ./src/asmgen/mod.rs:397:18
  24: <kecc::asmgen::Asmgen as kecc::utils::Translate<kecc::ir::TranslationUnit>>::translate
             at ./src/asmgen/mod.rs:141:23
  25: kecc::compile_ir
             at ./bin/kecc.rs:222:27
  26: kecc::main
             at ./bin/kecc.rs:99:9
  27: core::ops::function::FnOnce::call_once
             at /rustc/c475e2303b551d726307c646181e0677af1e0069/library/core/src/ops/function.rs:250:5